keys:
  - &users:
    - &jesse A378B0799F0593C0B499DD028FB4E35FE86B913B
  - &hosts:
    - &yu age1ukxx3kscch4e3tasyf28aamwdacsu7m3c2gqvyev0rvxsuvrydfsfxe44y
creation_rules:
  - path_regex: nixos/(common|features)/.*/secrets.ya?ml$
    key_groups:
      - age:
        - *yu
        pgp:
        - *jesse
